# Generated by Django 2.0.3 on 2018-04-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ManyToManyField(blank=True, help_text='Destinations accessible by this route', to='planner.Destination', verbose_name='Accessible Destination(s)'),
        ),
    ]
