# Generated by Django 2.0.3 on 2018-04-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20180331_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governingbody',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
