# Generated by Django 2.0.3 on 2018-04-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20180331_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='governingbody',
            name='abbr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
