# Generated by Django 2.0.3 on 2018-09-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20180908_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivetimemajorcity',
            name='error_message',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
