# Generated by Django 2.0.3 on 2018-09-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_drivetimemajorcity_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailhead',
            name='majorcity',
            field=models.ManyToManyField(through='planner.DriveTimeMajorCity', to='planner.MajorCity'),
        ),
    ]
