# Generated by Django 2.0.3 on 2018-04-08 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_governingbody_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.County'),
        ),
    ]
