# Generated by Django 2.0.3 on 2018-10-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('planner', '0005_trailhead_majorcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterField(
            model_name='drivetimemajorcity',
            name='trailhead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_data', to='planner.Trailhead'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Destination'),
        ),
        migrations.AlterField(
            model_name='route',
            name='path_seq',
            field=models.CharField(choices=[('oab', 'Out-And-Back'), ('ow', 'Through Hike'), ('l', 'Loop')], max_length=3, verbose_name='Route Sequence'),
        ),
    ]
