# Generated by Django 2.0.3 on 2018-11-02 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0007_auto_20181029_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('link_type', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], max_length=2)),
                ('owner_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Destination', verbose_name='Destination')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='publiclink',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='PublicLink',
        ),
    ]
