# Generated by Django 2.1.3 on 2018-11-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_routelink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='destinationlink',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='governingbody',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='jurisdiction',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='routelink',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='trailhead',
            options={'ordering': ['name']},
        ),
    ]
